backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: theatre
    label: Theatre
    folder: data/theatre/
    extension: .yml
    format: yaml
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Actors, name: actors, widget: string}
      - {label: Link, name: link, widget: string}
      - {label: Producers, name: producers, widget: string}
      - {label: Front Image, name: front_image, widget: image}
      - {label: Images, name: images, widget: list, field: {label: Image, name: path, widget: image}}
      - {label: Body, name: body, widget: markdown}
